import type { Metadata } from "next";
import "../ui/globals.css";
import SideBar from "../ui/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html className="h-full bg-gray-900">
      <body className={"h-full"}>
        <SideBar />
        {children}
      </body>
    </html>
  );
}
