import type { Metadata } from "next";
import "@/app/ui/globals.css";
import { logout } from "@/app/lib/actions";
import SideBar from "@/app/(admin)/ui/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html className="h-full bg-gray-900">
      <body className={"h-full"}>
        <SideBar logout={logout} />
        {children}
      </body>
    </html>
  );
}
