import type { Metadata } from "next";
import "@/app/ui/globals.css";
import { logout } from "@/app/lib/actions";
import SideBar from "@/app/(admin)/ui/side-bar";
import { auth } from "@/auth";
import { User } from "@/app/lib/definitions";

export const metadata: Metadata = {
  title: "Artfact",
  description: "Generated by Beinus & Bold",
};

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  const user = session?.user;
  if (!user) return;
  return (
    <html className="h-full bg-gray-900">
      <body className={"h-full"}>
        <SideBar logout={logout} user={user as unknown as User} />
        {children}
      </body>
    </html>
  );
}
